-- MySQL Script generated by MySQL Workbench
-- 11/29/17 16:27:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homeManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema homeManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeManagement` ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema new_schema2
-- -----------------------------------------------------
USE `homeManagement` ;

-- -----------------------------------------------------
-- Table `homeManagement`.`user_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeManagement`.`user_base` (
  `user_id` INT(100) NOT NULL COMMENT '用户id',
  `user_name` VARCHAR(45) NULL DEFAULT '未命名' COMMENT '用户名字',
  `user_type` ENUM('normal', 'admin') NOT NULL DEFAULT 'normal' COMMENT '用户类型',
  `user_introduce` TEXT(200) NULL COMMENT '用户简介',
  `user_password` VARCHAR(45) NOT NULL COMMENT '用户密码',
  `user_img` VARCHAR(45) NULL,
  `user_token` INT(45) NULL,
  `home_id` INT(100) NULL COMMENT '家庭ID',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeManagement`.`home_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeManagement`.`home_base` (
  `home_id` INT(100) NOT NULL COMMENT '家庭ID',
  `home_name` VARCHAR(45) NULL DEFAULT '未命名' COMMENT '家庭名字',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '家庭创建时间',
  `home_introduce` TEXT(200) NULL COMMENT '家庭简介',
  PRIMARY KEY (`home_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeManagement`.`home_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeManagement`.`home_member` (
  `home_id` INT(100) NOT NULL COMMENT '家庭ID',
  `user_id` INT(100) NOT NULL COMMENT '用户ID',
  `user_name` VARCHAR(45) NULL DEFAULT '未命名' COMMENT '用户名',
  `user_type` ENUM('normal', 'admin') NOT NULL DEFAULT 'norma' COMMENT '用户类型',
  `user_introduce` TEXT(200) NULL COMMENT '用户简介',
  `user_img` VARCHAR(45) NULL COMMENT '用户头像')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeManagement`.`home_funds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeManagement`.`home_funds` (
  `home_funds_id` INT(100) NOT NULL COMMENT '家庭资金id',
  `home_id` INT(100) NOT NULL COMMENT '家庭id',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '资金创建时间',
  `year_income` INT(11) NULL COMMENT '年收入',
  `month_income` INT(11) NULL COMMENT '月收入',
  `day_inconme` INT(11) NULL COMMENT '日收入',
  `year_consume` INT(11) NULL COMMENT '年消费',
  `month_consume` INT(11) NULL COMMENT '月消费',
  `day_consume` INT(11) NULL COMMENT '日消费',
  `year_earnings` INT(11) NULL COMMENT '年收益',
  `month_earnings` INT(11) NULL COMMENT '月收益',
  `day_earnings` INT(11) NULL COMMENT '日收益',
  PRIMARY KEY (`home_funds_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeManagement`.`home_funds_deal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeManagement`.`home_funds_deal` (
  `deal_id` INT(45) NOT NULL COMMENT '交易ID',
  `home_id` INT(45) NULL COMMENT '家庭ID',
  `deal_price` INT(11) NULL COMMENT '交易价钱',
  `deal_name` VARCHAR(45) NULL DEFAULT '未命名' COMMENT '交易名字',
  `deal_introduction` TEXT(200) NULL COMMENT '交易说明',
  `deal_type` ENUM('income', 'expend') NOT NULL COMMENT '交易类型：\n   income 收入\n   expend 支出',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '交易创建时间',
  PRIMARY KEY (`deal_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
